server:
 port: 8870
spring:
 datasource:
  url: jdbc:mysql://localhost/imssdb
  username: imssdb
  password: 12345678
  driver-class-name: com.mysql.jdbc.Driver
 jpa:
  database-platform: org.hibernate.dialect.MySQL5Dialect
  show-sql: true
  hibernate: 
   ddl-auto: none
management:
 endpoints:
  web:
   exposure:
    include: hystrix.stream, info, health, turbine.stream
eureka:
 client:
  serviceUrl:
   defaultZone: http://lstktr76754.stkrursus.com:8762/eureka/,http://lstktr76754.stkrursus.com:8763/eureka/,http://lstktr76754.stkrursus.com:8764/eureka/
 instance:
  metadata-map:
   instanceId: ${spring.Application.name}:${server.port}/	
